package:
    name: jasper
    version: 2.0.12

source:
    fn: jasper-2.0.12.tar.gz
    url: http://www.ece.uvic.ca/~frodo/jasper/software/jasper-2.0.12.tar.gz

build:
    number: '2.0.12'
    string: 'intel'

requirements:
    build:
    run:

about:
    home: http://www.ece.uvic.ca/~frodo/jasper
    
