package:
    name: wrfda
    version: 3.9.0

source:
    fn: WRFDA_V3.9.tar.gz
    url: http://www2.mmm.ucar.edu/wrf/src/WRFDA_V3.9.tar.gz

build:
    name: '0'

requirements:
    build:
        - netcdf ==4.4.1.1
        - netcdf-fortran ==4.4.4 2
    run:

about:
    home: http://www.mmm.ucar.edu
