package:
    name: wradlib
    version: 0.10.2

source:
    fn: wradlib-0.10.2
    url: https://github.com/wradlib/wradlib/archive/master.zip

build:
    number: '0.10.2'
    string: 'py27_0'

requirements:
    build:
        - numpy >=1.10.1
        - matplotlib >=1.5.1
        - scipy >=0.17.0
        - h5py >=2.5.0
        - netcdf4 >=1.2.2
        - gdal >=2.1.0 py27_0
        - xmltodict >=0.11.0 py27_0
    run:

about:
    home: http://www.mmm.ucar.edu
