package:
    name: zlib
    version: 1.2.9

source:
    fn: zlib-1.2.9.tar.gz
    url: https://sourceforge.net/projects/libpng/files/zlib/1.2.9/zlib-1.2.9.tar.gz

build:
    number: '1.2.9'
    string: 'intel'
    script_env:
        - INTEL

requirements:
    build:
    run:

about:
    home: http://www.zlib.net
    
