package:
    name: netcdf
    version: 4.4.1.1

source:
    fn: netcdf-4.4.1.1.tar.gz
    url: file://home/jzanetti/Downloads/netcdf-4.4.1.1.tar.gz

build:
    number: '4.4.1.1'
    string: 'intel'

requirements:
    build:
    run:

about:
    home: http://www2.mmm.ucar.edu/wrf
    
