package:
    name: netcdf
    version: 4.4.1.1

source:
    fn: netcdf-4.4.1.1.tar.gz
    url: ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-4.4.1.1.tar.gz

build:
    number: '4.4.1.1'
    string: 'intel'
    script_env:
        - INTEL

requirements:
    build:
       - hdf5 ==1.8.19 intel
    run:

about:
    home: http://www2.mmm.ucar.edu/wrf
    
